// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 48730 $
// File generated on 22/05/2012 10:26:33 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Windows\System32\msdatsrc.tlb (1)
// LIBID: {7C0FFAB0-CD84-11D0-949A-00A0C91110ED}
// LCID: 0
// Helpfile: 
// HelpString: Microsoft Data Source Interfaces for ActiveX Data Binding Type Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// Parent TypeLibrary:
//   (0) v9.0 Access, (XP\MSACC.olb)
// SYS_KIND: SYS_WIN32
// Cmdline:
//   tlibimp  -C+ -Fe_XP -CE_XP_SRVR -Ha- -Hr+ -HpsOfficeXP -Yp+ -D.\cppXP -Cv-   -HpcForm -HpcReferences -HpcReport XP\MSACC.olb
// ************************************************************************ //
#ifndef   MSDATASRC_XP_SRVRH
#define   MSDATASRC_XP_SRVRH

#pragma option push -b -a4 -w-inl -w-8118

#include <oleserver.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <System.Win.StdVCL.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "MSDATASRC_XP.h"
namespace Msdatasrc_xp
{

// *********************************************************************//
// HelpString: Microsoft Data Source Interfaces for ActiveX Data Binding Type Library
// Version:    1.0
// *********************************************************************//

};     // namespace Msdatasrc_xp

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Msdatasrc_xp;
#endif

#pragma option pop

#endif // MSDATASRC_XP_SRVRH
