// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 92848 $
// File generated on 4/23/2018 11:40:32 PM from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Windows\system32\shdocvw.dll (1)
// LIBID: {EAB22AC0-30C1-11CF-A7EB-0000C05BAE0B}
// LCID: 0
// Helpfile: 
// HelpString: Microsoft Internet Controls
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// SYS_KIND: SYS_WIN32
// Cmdline:
//   tlibimp  -C+ -G+ -Cv- -HpaInternet -HpsServers -D.\cppie5 C:\Windows\system32\shdocvw.dll
// ************************************************************************ //
#ifndef   SHDocVw_OCXH
#define   SHDocVw_OCXH

#pragma option push -b -w-inl -w-8118
#pragma pack(push, 4)

#include <Vcl.OleCtrls.hpp>
#include <Vcl.OleServer.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <System.Win.StdVCL.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "SHDocVw_TLB.h"
namespace Shdocvw_tlb
{

// *********************************************************************//
// HelpString: Microsoft Internet Controls
// Version:    1.1
// *********************************************************************//

// SKIPPING COCLASS: WebBrowser_V1        - Excluded via TLIBIMP.SYM file
// SKIPPING COCLASS: ShellBrowserWindow   - Has 'Hidden' flag
// SKIPPING COCLASS: CScriptErrorList     - Has 'Hidden' flag

// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TCppWebBrowser
// Help String      : WebBrowser Control
// Default Interface: IWebBrowser2
// Def. Intf. Object: IWebBrowser2Disp
// Def. Intf. DISP? : No
// Event   Interface: DWebBrowserEvents2
// TypeFlags        : (34) CanCreate Control
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
typedef void __fastcall (__closure * TCppWebBrowserStatusTextChange)(System::TObject * Sender, 
                                                                     BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserProgressChange)(System::TObject * Sender, 
                                                                   long Progress/*[in]*/, 
                                                                   long ProgressMax/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserCommandStateChange)(System::TObject * Sender, 
                                                                       long Command/*[in]*/, 
                                                                       VARIANT_BOOL Enable/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserTitleChange)(System::TObject * Sender, 
                                                                BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserPropertyChange)(System::TObject * Sender, 
                                                                   BSTR szProperty/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserBeforeNavigate2)(System::TObject * Sender, 
                                                                    LPDISPATCH pDisp/*[in]*/, 
                                                                    VARIANT* URL/*[in]*/, 
                                                                    VARIANT* Flags/*[in]*/, 
                                                                    VARIANT* TargetFrameName/*[in]*/, 
                                                                    VARIANT* PostData/*[in]*/, 
                                                                    VARIANT* Headers/*[in]*/, 
                                                                    VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserNewWindow2)(System::TObject * Sender, 
                                                               LPDISPATCH* ppDisp/*[in,out]*/, 
                                                               VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserNavigateComplete2)(System::TObject * Sender, 
                                                                      LPDISPATCH pDisp/*[in]*/, 
                                                                      VARIANT* URL/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserDocumentComplete)(System::TObject * Sender, 
                                                                     LPDISPATCH pDisp/*[in]*/, 
                                                                     VARIANT* URL/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserOnVisible)(System::TObject * Sender, 
                                                              VARIANT_BOOL Visible/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserOnToolBar)(System::TObject * Sender, 
                                                              VARIANT_BOOL ToolBar/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserOnMenuBar)(System::TObject * Sender, 
                                                              VARIANT_BOOL MenuBar/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserOnStatusBar)(System::TObject * Sender, 
                                                                VARIANT_BOOL StatusBar/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserOnFullScreen)(System::TObject * Sender, 
                                                                 VARIANT_BOOL FullScreen/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserOnTheaterMode)(System::TObject * Sender, 
                                                                  VARIANT_BOOL TheaterMode/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowSetResizable)(System::TObject * Sender, 
                                                                       VARIANT_BOOL Resizable/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowSetLeft)(System::TObject * Sender, 
                                                                  long Left/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowSetTop)(System::TObject * Sender, 
                                                                 long Top/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowSetWidth)(System::TObject * Sender, 
                                                                   long Width/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowSetHeight)(System::TObject * Sender, 
                                                                    long Height/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowClosing)(System::TObject * Sender, 
                                                                  VARIANT_BOOL IsChildWindow/*[in]*/, 
                                                                  VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserClientToHostWindow)(System::TObject * Sender, 
                                                                       long* CX/*[in,out]*/, 
                                                                       long* CY/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserSetSecureLockIcon)(System::TObject * Sender, 
                                                                      long SecureLockIcon/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserFileDownload)(System::TObject * Sender, 
                                                                 VARIANT_BOOL ActiveDocument/*[in]*/, 
                                                                 VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserNavigateError)(System::TObject * Sender, 
                                                                  LPDISPATCH pDisp/*[in]*/, 
                                                                  VARIANT* URL/*[in]*/, 
                                                                  VARIANT* Frame/*[in]*/, 
                                                                  VARIANT* StatusCode/*[in]*/, 
                                                                  VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserPrintTemplateInstantiation)(System::TObject * Sender, 
                                                                               LPDISPATCH pDisp/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserPrintTemplateTeardown)(System::TObject * Sender, 
                                                                          LPDISPATCH pDisp/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserUpdatePageStatus)(System::TObject * Sender, 
                                                                     LPDISPATCH pDisp/*[in]*/, 
                                                                     VARIANT* nPage/*[in]*/, 
                                                                     VARIANT* fDone/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserPrivacyImpactedStateChange)(System::TObject * Sender, 
                                                                               VARIANT_BOOL bImpacted/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserNewWindow3)(System::TObject * Sender, 
                                                               LPDISPATCH* ppDisp/*[in,out]*/, 
                                                               VARIANT_BOOL* Cancel/*[in,out]*/, 
                                                               unsigned_long dwFlags/*[in]*/, 
                                                               BSTR bstrUrlContext/*[in]*/, 
                                                               BSTR bstrUrl/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserSetPhishingFilterStatus)(System::TObject * Sender, 
                                                                            long PhishingFilterStatus/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserWindowStateChanged)(System::TObject * Sender, 
                                                                       unsigned_long dwWindowStateFlags/*[in]*/, 
                                                                       unsigned_long dwValidFlagsMask/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserNewProcess)(System::TObject * Sender, 
                                                               long lCauseFlag/*[in]*/, 
                                                               LPDISPATCH pWB2/*[in]*/, 
                                                               VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppWebBrowserThirdPartyUrlBlocked)(System::TObject * Sender, 
                                                                         VARIANT* URL/*[in]*/, 
                                                                         unsigned_long dwCount/*[in]*/);
typedef void __fastcall (__closure * TCppWebBrowserRedirectXDomainBlocked)(System::TObject * Sender, 
                                                                           LPDISPATCH pDisp/*[in]*/, 
                                                                           VARIANT* StartURL/*[in]*/, 
                                                                           VARIANT* RedirectURL/*[in]*/, 
                                                                           VARIANT* Frame/*[in]*/, 
                                                                           VARIANT* StatusCode/*[in]*/);
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host WebBrowser Control in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TCppWebBrowser : public Vcl::Olectrls::TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //
  TCppWebBrowserStatusTextChange FOnStatusTextChange;
  TCppWebBrowserProgressChange   FOnProgressChange;
  TCppWebBrowserCommandStateChange FOnCommandStateChange;
  System::Classes::TNotifyEvent  FOnDownloadBegin;
  System::Classes::TNotifyEvent  FOnDownloadComplete;
  TCppWebBrowserTitleChange      FOnTitleChange;
  TCppWebBrowserPropertyChange   FOnPropertyChange;
  TCppWebBrowserBeforeNavigate2  FOnBeforeNavigate2;
  TCppWebBrowserNewWindow2       FOnNewWindow2;
  TCppWebBrowserNavigateComplete2 FOnNavigateComplete2;
  TCppWebBrowserDocumentComplete FOnDocumentComplete;
  System::Classes::TNotifyEvent  FOnQuit;
  TCppWebBrowserOnVisible        FOnVisible;
  TCppWebBrowserOnToolBar        FOnToolBar;
  TCppWebBrowserOnMenuBar        FOnMenuBar;
  TCppWebBrowserOnStatusBar      FOnStatusBar;
  TCppWebBrowserOnFullScreen     FOnFullScreen;
  TCppWebBrowserOnTheaterMode    FOnTheaterMode;
  TCppWebBrowserWindowSetResizable FOnWindowSetResizable;
  TCppWebBrowserWindowSetLeft    FOnWindowSetLeft;
  TCppWebBrowserWindowSetTop     FOnWindowSetTop;
  TCppWebBrowserWindowSetWidth   FOnWindowSetWidth;
  TCppWebBrowserWindowSetHeight  FOnWindowSetHeight;
  TCppWebBrowserWindowClosing    FOnWindowClosing;
  TCppWebBrowserClientToHostWindow FOnClientToHostWindow;
  TCppWebBrowserSetSecureLockIcon FOnSetSecureLockIcon;
  TCppWebBrowserFileDownload     FOnFileDownload;
  TCppWebBrowserNavigateError    FOnNavigateError;
  TCppWebBrowserPrintTemplateInstantiation FOnPrintTemplateInstantiation;
  TCppWebBrowserPrintTemplateTeardown FOnPrintTemplateTeardown;
  TCppWebBrowserUpdatePageStatus FOnUpdatePageStatus;
  TCppWebBrowserPrivacyImpactedStateChange FOnPrivacyImpactedStateChange;
  TCppWebBrowserNewWindow3       FOnNewWindow3;
  TCppWebBrowserSetPhishingFilterStatus FOnSetPhishingFilterStatus;
  TCppWebBrowserWindowStateChanged FOnWindowStateChanged;
  TCppWebBrowserNewProcess       FOnNewProcess;
  TCppWebBrowserThirdPartyUrlBlocked FOnThirdPartyUrlBlocked;
  TCppWebBrowserRedirectXDomainBlocked FOnRedirectXDomainBlocked;

  // Default Interace of OCX
  //
  IWebBrowser2Disp m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Application(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Parent(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Container(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Document(void);
    // StdProp:
  long            __fastcall get_HWND(void);

  // Static variables used by all instances of OCX proxy
  //
  static int          EventDispIDs[38];
  static Vcl::Olectrls::TControlData2 CControlData;
  static GUID          CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  IWebBrowser2Disp __fastcall GetDefaultInterface();
  IWebBrowser2Disp __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TCppWebBrowser(System::Classes::TComponent* AOwner) : Vcl::Olectrls::TOleControl(AOwner)
  {};
  virtual  __fastcall TCppWebBrowser(HWND        Parent) : Vcl::Olectrls::TOleControl(Parent)
  {};

  // OCX methods
  //
  void            __fastcall GoBack(void);
  void            __fastcall GoForward(void);
  void            __fastcall GoHome(void);
  void            __fastcall GoSearch(void);
  void            __fastcall Navigate(BSTR URL/*[in]*/, VARIANT* Flags/*[in,opt]*/= TNoParam(), 
                                      VARIANT* TargetFrameName/*[in,opt]*/= TNoParam(), 
                                      VARIANT* PostData/*[in,opt]*/= TNoParam(), 
                                      VARIANT* Headers/*[in,opt]*/= TNoParam());
  void            __fastcall Refresh(void);
  void            __fastcall Refresh2(VARIANT* Level/*[in,opt]*/= TNoParam());
  void            __fastcall Stop(void);
  void            __fastcall Quit(void);
  void            __fastcall ClientToWindow(int* pcx/*[in,out]*/, int* pcy/*[in,out]*/);
  void            __fastcall PutProperty(BSTR Property/*[in]*/, VARIANT vtValue/*[in]*/);
  VARIANT         __fastcall GetProperty(BSTR Property/*[in]*/);
  void            __fastcall Navigate2(VARIANT* URL/*[in]*/, VARIANT* Flags/*[in,opt]*/= TNoParam(), 
                                       VARIANT* TargetFrameName/*[in,opt]*/= TNoParam(), 
                                       VARIANT* PostData/*[in,opt]*/= TNoParam(), 
                                       VARIANT* Headers/*[in,opt]*/= TNoParam());
  Shdocvw_tlb::OLECMDF __fastcall QueryStatusWB(Shdocvw_tlb::OLECMDID cmdID/*[in]*/);
  void            __fastcall ExecWB(Shdocvw_tlb::OLECMDID cmdID/*[in]*/, 
                                    Shdocvw_tlb::OLECMDEXECOPT cmdexecopt/*[in]*/, 
                                    VARIANT* pvaIn/*[in,opt]*/= TNoParam(), 
                                    VARIANT* pvaOut/*[in,out,opt]*/= TNoParam());
  void            __fastcall ShowBrowserBar(VARIANT* pvaClsid/*[in]*/, 
                                            VARIANT* pvarShow/*[in,opt]*/= TNoParam(), 
                                            VARIANT* pvarSize/*[in,opt]*/= TNoParam());

  // OCX properties
  //
  __property _di_IDispatch Application={ read=GetIDispatchProp, index=200 }; // STDPROP:8, INTF:No, INVK:2, ID:200, ASSID:200
  __property _di_IDispatch Parent={ read=GetIDispatchProp, index=201 }; // STDPROP:8, INTF:No, INVK:2, ID:201, ASSID:201
  __property _di_IDispatch Container={ read=GetIDispatchProp, index=202 }; // STDPROP:8, INTF:No, INVK:2, ID:202, ASSID:202
  __property _di_IDispatch Document={ read=GetIDispatchProp, index=203 }; // STDPROP:8, INTF:No, INVK:2, ID:203, ASSID:203
  __property bool TopLevelContainer={ read=GetWordBoolProp, index=204 }; // STDPROP:9, INTF:No, INVK:2, ID:204, ASSID:204
  __property System::WideString Type={ read=GetWideStringProp, index=205 }; // STDPROP:7, INTF:No, INVK:2, ID:205, ASSID:205
  __property System::WideString LocationName={ read=GetWideStringProp, index=210 }; // STDPROP:7, INTF:No, INVK:2, ID:210, ASSID:210
  __property System::WideString LocationURL={ read=GetWideStringProp, index=211 }; // STDPROP:7, INTF:No, INVK:2, ID:211, ASSID:211
  __property bool Busy={ read=GetWordBoolProp, index=212 }; // STDPROP:9, INTF:No, INVK:2, ID:212, ASSID:212
  __property System::WideString Name={ read=GetWideStringProp, index=0 }; // STDPROP:7, INTF:No, INVK:2, ID:0, ASSID:0
  __property long HWND={ read=get_HWND }; // STDPROP:0, INTF:No, INVK:2, ID:-515, ASSID:-515
  __property System::WideString FullName={ read=GetWideStringProp, index=400 }; // STDPROP:7, INTF:No, INVK:2, ID:400, ASSID:400
  __property System::WideString Path={ read=GetWideStringProp, index=401 }; // STDPROP:7, INTF:No, INVK:2, ID:401, ASSID:401
  __property Winapi::Activex::TOleEnum ReadyState={ read=GetTOleEnumProp, index=-525 }; // STDPROP:16, INTF:No, INVK:2, ID:-525, ASSID:-525
  __property IWebBrowser2Disp ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property TabStop;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;

  // OCX properties
  //
  __property bool Visible={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=402 }; // STDPROP:9, INTF:No, INVK:2, ID:402, ASSID:402
  __property bool StatusBar={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=403 }; // STDPROP:9, INTF:No, INVK:2, ID:403, ASSID:403
  __property System::WideString StatusText={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=404 }; // STDPROP:7, INTF:No, INVK:2, ID:404, ASSID:404
  __property int ToolBar={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=405 }; // STDPROP:2, INTF:No, INVK:2, ID:405, ASSID:405
  __property bool MenuBar={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=406 }; // STDPROP:9, INTF:No, INVK:2, ID:406, ASSID:406
  __property bool FullScreen={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=407 }; // STDPROP:9, INTF:No, INVK:2, ID:407, ASSID:407
  __property bool Offline={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=550 }; // STDPROP:9, INTF:No, INVK:2, ID:550, ASSID:550
  __property bool Silent={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=551 }; // STDPROP:9, INTF:No, INVK:2, ID:551, ASSID:551
  __property bool RegisterAsBrowser={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=552 }; // STDPROP:9, INTF:No, INVK:2, ID:552, ASSID:552
  __property bool RegisterAsDropTarget={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=553 }; // STDPROP:9, INTF:No, INVK:2, ID:553, ASSID:553
  __property bool TheaterMode={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=554 }; // STDPROP:9, INTF:No, INVK:2, ID:554, ASSID:554
  __property bool AddressBar={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=555 }; // STDPROP:9, INTF:No, INVK:2, ID:555, ASSID:555
  __property bool Resizable={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=556 }; // STDPROP:9, INTF:No, INVK:2, ID:556, ASSID:556

  // OCX Events
  //
  __property TCppWebBrowserStatusTextChange OnStatusTextChange={ read=FOnStatusTextChange, write=FOnStatusTextChange };
  __property TCppWebBrowserProgressChange OnProgressChange={ read=FOnProgressChange, write=FOnProgressChange };
  __property TCppWebBrowserCommandStateChange OnCommandStateChange={ read=FOnCommandStateChange, write=FOnCommandStateChange };
  __property System::Classes::TNotifyEvent OnDownloadBegin={ read=FOnDownloadBegin, write=FOnDownloadBegin };
  __property System::Classes::TNotifyEvent OnDownloadComplete={ read=FOnDownloadComplete, write=FOnDownloadComplete };
  __property TCppWebBrowserTitleChange OnTitleChange={ read=FOnTitleChange, write=FOnTitleChange };
  __property TCppWebBrowserPropertyChange OnPropertyChange={ read=FOnPropertyChange, write=FOnPropertyChange };
  __property TCppWebBrowserBeforeNavigate2 OnBeforeNavigate2={ read=FOnBeforeNavigate2, write=FOnBeforeNavigate2 };
  __property TCppWebBrowserNewWindow2 OnNewWindow2={ read=FOnNewWindow2, write=FOnNewWindow2 };
  __property TCppWebBrowserNavigateComplete2 OnNavigateComplete2={ read=FOnNavigateComplete2, write=FOnNavigateComplete2 };
  __property TCppWebBrowserDocumentComplete OnDocumentComplete={ read=FOnDocumentComplete, write=FOnDocumentComplete };
  __property System::Classes::TNotifyEvent OnQuit={ read=FOnQuit, write=FOnQuit };
  __property TCppWebBrowserOnVisible OnVisible={ read=FOnVisible, write=FOnVisible };
  __property TCppWebBrowserOnToolBar OnToolBar={ read=FOnToolBar, write=FOnToolBar };
  __property TCppWebBrowserOnMenuBar OnMenuBar={ read=FOnMenuBar, write=FOnMenuBar };
  __property TCppWebBrowserOnStatusBar OnStatusBar={ read=FOnStatusBar, write=FOnStatusBar };
  __property TCppWebBrowserOnFullScreen OnFullScreen={ read=FOnFullScreen, write=FOnFullScreen };
  __property TCppWebBrowserOnTheaterMode OnTheaterMode={ read=FOnTheaterMode, write=FOnTheaterMode };
  __property TCppWebBrowserWindowSetResizable OnWindowSetResizable={ read=FOnWindowSetResizable, write=FOnWindowSetResizable };
  __property TCppWebBrowserWindowSetLeft OnWindowSetLeft={ read=FOnWindowSetLeft, write=FOnWindowSetLeft };
  __property TCppWebBrowserWindowSetTop OnWindowSetTop={ read=FOnWindowSetTop, write=FOnWindowSetTop };
  __property TCppWebBrowserWindowSetWidth OnWindowSetWidth={ read=FOnWindowSetWidth, write=FOnWindowSetWidth };
  __property TCppWebBrowserWindowSetHeight OnWindowSetHeight={ read=FOnWindowSetHeight, write=FOnWindowSetHeight };
  __property TCppWebBrowserWindowClosing OnWindowClosing={ read=FOnWindowClosing, write=FOnWindowClosing };
  __property TCppWebBrowserClientToHostWindow OnClientToHostWindow={ read=FOnClientToHostWindow, write=FOnClientToHostWindow };
  __property TCppWebBrowserSetSecureLockIcon OnSetSecureLockIcon={ read=FOnSetSecureLockIcon, write=FOnSetSecureLockIcon };
  __property TCppWebBrowserFileDownload OnFileDownload={ read=FOnFileDownload, write=FOnFileDownload };
  __property TCppWebBrowserNavigateError OnNavigateError={ read=FOnNavigateError, write=FOnNavigateError };
  __property TCppWebBrowserPrintTemplateInstantiation OnPrintTemplateInstantiation={ read=FOnPrintTemplateInstantiation, write=FOnPrintTemplateInstantiation };
  __property TCppWebBrowserPrintTemplateTeardown OnPrintTemplateTeardown={ read=FOnPrintTemplateTeardown, write=FOnPrintTemplateTeardown };
  __property TCppWebBrowserUpdatePageStatus OnUpdatePageStatus={ read=FOnUpdatePageStatus, write=FOnUpdatePageStatus };
  __property TCppWebBrowserPrivacyImpactedStateChange OnPrivacyImpactedStateChange={ read=FOnPrivacyImpactedStateChange, write=FOnPrivacyImpactedStateChange };
  __property TCppWebBrowserNewWindow3 OnNewWindow3={ read=FOnNewWindow3, write=FOnNewWindow3 };
  __property TCppWebBrowserSetPhishingFilterStatus OnSetPhishingFilterStatus={ read=FOnSetPhishingFilterStatus, write=FOnSetPhishingFilterStatus };
  __property TCppWebBrowserWindowStateChanged OnWindowStateChanged={ read=FOnWindowStateChanged, write=FOnWindowStateChanged };
  __property TCppWebBrowserNewProcess OnNewProcess={ read=FOnNewProcess, write=FOnNewProcess };
  __property TCppWebBrowserThirdPartyUrlBlocked OnThirdPartyUrlBlocked={ read=FOnThirdPartyUrlBlocked, write=FOnThirdPartyUrlBlocked };
  __property TCppWebBrowserRedirectXDomainBlocked OnRedirectXDomainBlocked={ read=FOnRedirectXDomainBlocked, write=FOnRedirectXDomainBlocked };
};
typedef TCppWebBrowser  TCppWebBrowserProxy;


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TCppInternetExplorer
// Help String      : Internet Explorer Application.
// Default Interface: IWebBrowser2
// Def. Intf. Object: IWebBrowser2Ptr
// Def. Intf. DISP? : No
// Event   Interface: DWebBrowserEvents2
// TypeFlags        : (2) CanCreate
// *********************************************************************//
typedef void __fastcall (__closure * TCppInternetExplorerStatusTextChange)(System::TObject * Sender, 
                                                                           BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerProgressChange)(System::TObject * Sender, 
                                                                         long Progress/*[in]*/, 
                                                                         long ProgressMax/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerCommandStateChange)(System::TObject * Sender, 
                                                                             long Command/*[in]*/, 
                                                                             VARIANT_BOOL Enable/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerTitleChange)(System::TObject * Sender, 
                                                                      BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerPropertyChange)(System::TObject * Sender, 
                                                                         BSTR szProperty/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerBeforeNavigate2)(System::TObject * Sender, 
                                                                          LPDISPATCH pDisp/*[in]*/, 
                                                                          VARIANT* URL/*[in]*/, 
                                                                          VARIANT* Flags/*[in]*/, 
                                                                          VARIANT* TargetFrameName/*[in]*/, 
                                                                          VARIANT* PostData/*[in]*/, 
                                                                          VARIANT* Headers/*[in]*/, 
                                                                          VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerNewWindow2)(System::TObject * Sender, 
                                                                     LPDISPATCH* ppDisp/*[in,out]*/, 
                                                                     VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerNavigateComplete2)(System::TObject * Sender, 
                                                                            LPDISPATCH pDisp/*[in]*/, 
                                                                            VARIANT* URL/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerDocumentComplete)(System::TObject * Sender, 
                                                                           LPDISPATCH pDisp/*[in]*/, 
                                                                           VARIANT* URL/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerOnVisible)(System::TObject * Sender, 
                                                                    VARIANT_BOOL Visible/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerOnToolBar)(System::TObject * Sender, 
                                                                    VARIANT_BOOL ToolBar/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerOnMenuBar)(System::TObject * Sender, 
                                                                    VARIANT_BOOL MenuBar/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerOnStatusBar)(System::TObject * Sender, 
                                                                      VARIANT_BOOL StatusBar/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerOnFullScreen)(System::TObject * Sender, 
                                                                       VARIANT_BOOL FullScreen/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerOnTheaterMode)(System::TObject * Sender, 
                                                                        VARIANT_BOOL TheaterMode/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowSetResizable)(System::TObject * Sender, 
                                                                             VARIANT_BOOL Resizable/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowSetLeft)(System::TObject * Sender, 
                                                                        long Left/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowSetTop)(System::TObject * Sender, 
                                                                       long Top/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowSetWidth)(System::TObject * Sender, 
                                                                         long Width/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowSetHeight)(System::TObject * Sender, 
                                                                          long Height/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowClosing)(System::TObject * Sender, 
                                                                        VARIANT_BOOL IsChildWindow/*[in]*/, 
                                                                        VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerClientToHostWindow)(System::TObject * Sender, 
                                                                             long* CX/*[in,out]*/, 
                                                                             long* CY/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerSetSecureLockIcon)(System::TObject * Sender, 
                                                                            long SecureLockIcon/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerFileDownload)(System::TObject * Sender, 
                                                                       VARIANT_BOOL ActiveDocument/*[in]*/, 
                                                                       VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerNavigateError)(System::TObject * Sender, 
                                                                        LPDISPATCH pDisp/*[in]*/, 
                                                                        VARIANT* URL/*[in]*/, 
                                                                        VARIANT* Frame/*[in]*/, 
                                                                        VARIANT* StatusCode/*[in]*/, 
                                                                        VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerPrintTemplateInstantiation)(System::TObject * Sender, 
                                                                                     LPDISPATCH pDisp/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerPrintTemplateTeardown)(System::TObject * Sender, 
                                                                                LPDISPATCH pDisp/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerUpdatePageStatus)(System::TObject * Sender, 
                                                                           LPDISPATCH pDisp/*[in]*/, 
                                                                           VARIANT* nPage/*[in]*/, 
                                                                           VARIANT* fDone/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerPrivacyImpactedStateChange)(System::TObject * Sender, 
                                                                                     VARIANT_BOOL bImpacted/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerNewWindow3)(System::TObject * Sender, 
                                                                     LPDISPATCH* ppDisp/*[in,out]*/, 
                                                                     VARIANT_BOOL* Cancel/*[in,out]*/, 
                                                                     unsigned_long dwFlags/*[in]*/, 
                                                                     BSTR bstrUrlContext/*[in]*/, 
                                                                     BSTR bstrUrl/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerSetPhishingFilterStatus)(System::TObject * Sender, 
                                                                                  long PhishingFilterStatus/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerWindowStateChanged)(System::TObject * Sender, 
                                                                             unsigned_long dwWindowStateFlags/*[in]*/, 
                                                                             unsigned_long dwValidFlagsMask/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerNewProcess)(System::TObject * Sender, 
                                                                     long lCauseFlag/*[in]*/, 
                                                                     LPDISPATCH pWB2/*[in]*/, 
                                                                     VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TCppInternetExplorerThirdPartyUrlBlocked)(System::TObject * Sender, 
                                                                               VARIANT* URL/*[in]*/, 
                                                                               unsigned_long dwCount/*[in]*/);
typedef void __fastcall (__closure * TCppInternetExplorerRedirectXDomainBlocked)(System::TObject * Sender, 
                                                                                 LPDISPATCH pDisp/*[in]*/, 
                                                                                 VARIANT* StartURL/*[in]*/, 
                                                                                 VARIANT* RedirectURL/*[in]*/, 
                                                                                 VARIANT* Frame/*[in]*/, 
                                                                                 VARIANT* StatusCode/*[in]*/);

class PACKAGE TCppInternetExplorer : public Vcl::Oleserver::TOleServer
{
  IWebBrowser2Ptr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TCppInternetExplorer(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  IWebBrowser2Ptr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IWebBrowser2Ptr intf);

  virtual void __fastcall InvokeEvent(int DispID, Vcl::Oleserver::TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Application(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Parent(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Container(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Document(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_TopLevelContainer(void);
    // StdProp:WideString
  BSTR            __fastcall get_Type(void);
    // StdProp:Integer
  long            __fastcall get_Left(void);
    // StdProp:Integer
  void            __fastcall set_Left(long pl/*[in]*/);
    // StdProp:Integer
  long            __fastcall get_Top(void);
    // StdProp:Integer
  void            __fastcall set_Top(long pl/*[in]*/);
    // StdProp:Integer
  long            __fastcall get_Width(void);
    // StdProp:Integer
  void            __fastcall set_Width(long pl/*[in]*/);
    // StdProp:Integer
  long            __fastcall get_Height(void);
    // StdProp:Integer
  void            __fastcall set_Height(long pl/*[in]*/);
    // StdProp:WideString
  BSTR            __fastcall get_LocationName(void);
    // StdProp:WideString
  BSTR            __fastcall get_LocationURL(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Busy(void);
    // StdProp:WideString
  BSTR            __fastcall get_Name(void);
    // StdProp:
  long            __fastcall get_HWND(void);
    // StdProp:WideString
  BSTR            __fastcall get_FullName(void);
    // StdProp:WideString
  BSTR            __fastcall get_Path(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Visible(void);
    // StdProp:WordBool
  void            __fastcall set_Visible(VARIANT_BOOL pBool/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_StatusBar(void);
    // StdProp:WordBool
  void            __fastcall set_StatusBar(VARIANT_BOOL pBool/*[in]*/);
    // StdProp:WideString
  BSTR            __fastcall get_StatusText(void);
    // StdProp:WideString
  void            __fastcall set_StatusText(BSTR StatusText/*[in]*/);
    // StdProp:Integer
  int             __fastcall get_ToolBar(void);
    // StdProp:Integer
  void            __fastcall set_ToolBar(int Value/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_MenuBar(void);
    // StdProp:WordBool
  void            __fastcall set_MenuBar(VARIANT_BOOL Value/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_FullScreen(void);
    // StdProp:WordBool
  void            __fastcall set_FullScreen(VARIANT_BOOL pbFullScreen/*[in]*/);
    // StdProp:TOleEnum
  Shdocvw_tlb::tagREADYSTATE __fastcall get_ReadyState(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Offline(void);
    // StdProp:WordBool
  void            __fastcall set_Offline(VARIANT_BOOL pbOffline/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Silent(void);
    // StdProp:WordBool
  void            __fastcall set_Silent(VARIANT_BOOL pbSilent/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_RegisterAsBrowser(void);
    // StdProp:WordBool
  void            __fastcall set_RegisterAsBrowser(VARIANT_BOOL pbRegister/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_RegisterAsDropTarget(void);
    // StdProp:WordBool
  void            __fastcall set_RegisterAsDropTarget(VARIANT_BOOL pbRegister/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_TheaterMode(void);
    // StdProp:WordBool
  void            __fastcall set_TheaterMode(VARIANT_BOOL pbRegister/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_AddressBar(void);
    // StdProp:WordBool
  void            __fastcall set_AddressBar(VARIANT_BOOL Value/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Resizable(void);
    // StdProp:WordBool
  void            __fastcall set_Resizable(VARIANT_BOOL Value/*[in]*/);
  /*CoClassWriteMethods*/
  void            __fastcall GoBack(void);
  void            __fastcall GoForward(void);
  void            __fastcall GoHome(void);
  void            __fastcall GoSearch(void);
  void            __fastcall Navigate(BSTR URL/*[in]*/, VARIANT* Flags/*[in,opt]*/= TNoParam(), 
                                      VARIANT* TargetFrameName/*[in,opt]*/= TNoParam(), 
                                      VARIANT* PostData/*[in,opt]*/= TNoParam(), 
                                      VARIANT* Headers/*[in,opt]*/= TNoParam());
  void            __fastcall Refresh(void);
  void            __fastcall Refresh2(VARIANT* Level/*[in,opt]*/= TNoParam());
  void            __fastcall Stop(void);
  void            __fastcall Quit(void);
  void            __fastcall ClientToWindow(int* pcx/*[in,out]*/, int* pcy/*[in,out]*/);
  void            __fastcall PutProperty(BSTR Property/*[in]*/, VARIANT vtValue/*[in]*/);
  VARIANT         __fastcall GetProperty(BSTR Property/*[in]*/);
  void            __fastcall Navigate2(VARIANT* URL/*[in]*/, VARIANT* Flags/*[in,opt]*/= TNoParam(), 
                                       VARIANT* TargetFrameName/*[in,opt]*/= TNoParam(), 
                                       VARIANT* PostData/*[in,opt]*/= TNoParam(), 
                                       VARIANT* Headers/*[in,opt]*/= TNoParam());
  Shdocvw_tlb::OLECMDF __fastcall QueryStatusWB(Shdocvw_tlb::OLECMDID cmdID/*[in]*/);
  void            __fastcall ExecWB(Shdocvw_tlb::OLECMDID cmdID/*[in]*/, 
                                    Shdocvw_tlb::OLECMDEXECOPT cmdexecopt/*[in]*/, 
                                    VARIANT* pvaIn/*[in,opt]*/= TNoParam(), 
                                    VARIANT* pvaOut/*[in,out,opt]*/= TNoParam());
  void            __fastcall ShowBrowserBar(VARIANT* pvaClsid/*[in]*/, 
                                            VARIANT* pvarShow/*[in,opt]*/= TNoParam(), 
                                            VARIANT* pvarSize/*[in,opt]*/= TNoParam());
  /*CoClassWriteProperties*/
  __property LPDISPATCH Application={ read=get_Application }; // STDPROP:0, INTF:No, INVK:2, ID:200, ASSID:200
  __property LPDISPATCH Parent={ read=get_Parent }; // STDPROP:0, INTF:No, INVK:2, ID:201, ASSID:201
  __property LPDISPATCH Container={ read=get_Container }; // STDPROP:0, INTF:No, INVK:2, ID:202, ASSID:202
  __property LPDISPATCH Document={ read=get_Document }; // STDPROP:0, INTF:No, INVK:2, ID:203, ASSID:203
  __property VARIANT_BOOL TopLevelContainer={ read=get_TopLevelContainer }; // STDPROP:0, INTF:No, INVK:2, ID:204, ASSID:204
  __property BSTR Type={ read=get_Type }; // STDPROP:0, INTF:No, INVK:2, ID:205, ASSID:205
  __property BSTR LocationName={ read=get_LocationName }; // STDPROP:0, INTF:No, INVK:2, ID:210, ASSID:210
  __property BSTR LocationURL={ read=get_LocationURL }; // STDPROP:0, INTF:No, INVK:2, ID:211, ASSID:211
  __property VARIANT_BOOL Busy={ read=get_Busy }; // STDPROP:0, INTF:No, INVK:2, ID:212, ASSID:212
  __property BSTR Name={ read=get_Name }; // STDPROP:0, INTF:No, INVK:2, ID:0, ASSID:0
  __property long HWND={ read=get_HWND }; // STDPROP:0, INTF:No, INVK:2, ID:-515, ASSID:-515
  __property BSTR FullName={ read=get_FullName }; // STDPROP:0, INTF:No, INVK:2, ID:400, ASSID:400
  __property BSTR Path={ read=get_Path }; // STDPROP:0, INTF:No, INVK:2, ID:401, ASSID:401
  __property Shdocvw_tlb::tagREADYSTATE ReadyState={ read=get_ReadyState }; // STDPROP:0, INTF:No, INVK:2, ID:-525, ASSID:-525
  /*CoClassWriteProperties*/
  __property long Left={ read=get_Left, write=set_Left, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:206, ASSID:206
  __property long Top={ read=get_Top, write=set_Top, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:207, ASSID:207
  __property long Width={ read=get_Width, write=set_Width, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:208, ASSID:208
  __property long Height={ read=get_Height, write=set_Height, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:209, ASSID:209
  __property VARIANT_BOOL Visible={ read=get_Visible, write=set_Visible, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:402, ASSID:402
  __property VARIANT_BOOL StatusBar={ read=get_StatusBar, write=set_StatusBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:403, ASSID:403
  __property BSTR StatusText={ read=get_StatusText, write=set_StatusText, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:404, ASSID:404
  __property int ToolBar={ read=get_ToolBar, write=set_ToolBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:405, ASSID:405
  __property VARIANT_BOOL MenuBar={ read=get_MenuBar, write=set_MenuBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:406, ASSID:406
  __property VARIANT_BOOL FullScreen={ read=get_FullScreen, write=set_FullScreen, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:407, ASSID:407
  __property VARIANT_BOOL Offline={ read=get_Offline, write=set_Offline, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:550, ASSID:550
  __property VARIANT_BOOL Silent={ read=get_Silent, write=set_Silent, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:551, ASSID:551
  __property VARIANT_BOOL RegisterAsBrowser={ read=get_RegisterAsBrowser, write=set_RegisterAsBrowser, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:552, ASSID:552
  __property VARIANT_BOOL RegisterAsDropTarget={ read=get_RegisterAsDropTarget, write=set_RegisterAsDropTarget, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:553, ASSID:553
  __property VARIANT_BOOL TheaterMode={ read=get_TheaterMode, write=set_TheaterMode, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:554, ASSID:554
  __property VARIANT_BOOL AddressBar={ read=get_AddressBar, write=set_AddressBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:555, ASSID:555
  __property VARIANT_BOOL Resizable={ read=get_Resizable, write=set_Resizable, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:556, ASSID:556
  /*CoClassWriteEventDecls*/
private:
  TCppInternetExplorerStatusTextChange FOnStatusTextChange;
  TCppInternetExplorerProgressChange FOnProgressChange;
  TCppInternetExplorerCommandStateChange FOnCommandStateChange;
  System::Classes::TNotifyEvent  FOnDownloadBegin;
  System::Classes::TNotifyEvent  FOnDownloadComplete;
  TCppInternetExplorerTitleChange FOnTitleChange;
  TCppInternetExplorerPropertyChange FOnPropertyChange;
  TCppInternetExplorerBeforeNavigate2 FOnBeforeNavigate2;
  TCppInternetExplorerNewWindow2 FOnNewWindow2;
  TCppInternetExplorerNavigateComplete2 FOnNavigateComplete2;
  TCppInternetExplorerDocumentComplete FOnDocumentComplete;
  System::Classes::TNotifyEvent  FOnQuit;
  TCppInternetExplorerOnVisible  FOnVisible;
  TCppInternetExplorerOnToolBar  FOnToolBar;
  TCppInternetExplorerOnMenuBar  FOnMenuBar;
  TCppInternetExplorerOnStatusBar FOnStatusBar;
  TCppInternetExplorerOnFullScreen FOnFullScreen;
  TCppInternetExplorerOnTheaterMode FOnTheaterMode;
  TCppInternetExplorerWindowSetResizable FOnWindowSetResizable;
  TCppInternetExplorerWindowSetLeft FOnWindowSetLeft;
  TCppInternetExplorerWindowSetTop FOnWindowSetTop;
  TCppInternetExplorerWindowSetWidth FOnWindowSetWidth;
  TCppInternetExplorerWindowSetHeight FOnWindowSetHeight;
  TCppInternetExplorerWindowClosing FOnWindowClosing;
  TCppInternetExplorerClientToHostWindow FOnClientToHostWindow;
  TCppInternetExplorerSetSecureLockIcon FOnSetSecureLockIcon;
  TCppInternetExplorerFileDownload FOnFileDownload;
  TCppInternetExplorerNavigateError FOnNavigateError;
  TCppInternetExplorerPrintTemplateInstantiation FOnPrintTemplateInstantiation;
  TCppInternetExplorerPrintTemplateTeardown FOnPrintTemplateTeardown;
  TCppInternetExplorerUpdatePageStatus FOnUpdatePageStatus;
  TCppInternetExplorerPrivacyImpactedStateChange FOnPrivacyImpactedStateChange;
  TCppInternetExplorerNewWindow3 FOnNewWindow3;
  TCppInternetExplorerSetPhishingFilterStatus FOnSetPhishingFilterStatus;
  TCppInternetExplorerWindowStateChanged FOnWindowStateChanged;
  TCppInternetExplorerNewProcess FOnNewProcess;
  TCppInternetExplorerThirdPartyUrlBlocked FOnThirdPartyUrlBlocked;
  TCppInternetExplorerRedirectXDomainBlocked FOnRedirectXDomainBlocked;
__published:
  __property TCppInternetExplorerStatusTextChange OnStatusTextChange={ read=FOnStatusTextChange, write=FOnStatusTextChange };
  __property TCppInternetExplorerProgressChange OnProgressChange={ read=FOnProgressChange, write=FOnProgressChange };
  __property TCppInternetExplorerCommandStateChange OnCommandStateChange={ read=FOnCommandStateChange, write=FOnCommandStateChange };
  __property System::Classes::TNotifyEvent OnDownloadBegin={ read=FOnDownloadBegin, write=FOnDownloadBegin };
  __property System::Classes::TNotifyEvent OnDownloadComplete={ read=FOnDownloadComplete, write=FOnDownloadComplete };
  __property TCppInternetExplorerTitleChange OnTitleChange={ read=FOnTitleChange, write=FOnTitleChange };
  __property TCppInternetExplorerPropertyChange OnPropertyChange={ read=FOnPropertyChange, write=FOnPropertyChange };
  __property TCppInternetExplorerBeforeNavigate2 OnBeforeNavigate2={ read=FOnBeforeNavigate2, write=FOnBeforeNavigate2 };
  __property TCppInternetExplorerNewWindow2 OnNewWindow2={ read=FOnNewWindow2, write=FOnNewWindow2 };
  __property TCppInternetExplorerNavigateComplete2 OnNavigateComplete2={ read=FOnNavigateComplete2, write=FOnNavigateComplete2 };
  __property TCppInternetExplorerDocumentComplete OnDocumentComplete={ read=FOnDocumentComplete, write=FOnDocumentComplete };
  __property System::Classes::TNotifyEvent OnQuit={ read=FOnQuit, write=FOnQuit };
  __property TCppInternetExplorerOnVisible OnVisible={ read=FOnVisible, write=FOnVisible };
  __property TCppInternetExplorerOnToolBar OnToolBar={ read=FOnToolBar, write=FOnToolBar };
  __property TCppInternetExplorerOnMenuBar OnMenuBar={ read=FOnMenuBar, write=FOnMenuBar };
  __property TCppInternetExplorerOnStatusBar OnStatusBar={ read=FOnStatusBar, write=FOnStatusBar };
  __property TCppInternetExplorerOnFullScreen OnFullScreen={ read=FOnFullScreen, write=FOnFullScreen };
  __property TCppInternetExplorerOnTheaterMode OnTheaterMode={ read=FOnTheaterMode, write=FOnTheaterMode };
  __property TCppInternetExplorerWindowSetResizable OnWindowSetResizable={ read=FOnWindowSetResizable, write=FOnWindowSetResizable };
  __property TCppInternetExplorerWindowSetLeft OnWindowSetLeft={ read=FOnWindowSetLeft, write=FOnWindowSetLeft };
  __property TCppInternetExplorerWindowSetTop OnWindowSetTop={ read=FOnWindowSetTop, write=FOnWindowSetTop };
  __property TCppInternetExplorerWindowSetWidth OnWindowSetWidth={ read=FOnWindowSetWidth, write=FOnWindowSetWidth };
  __property TCppInternetExplorerWindowSetHeight OnWindowSetHeight={ read=FOnWindowSetHeight, write=FOnWindowSetHeight };
  __property TCppInternetExplorerWindowClosing OnWindowClosing={ read=FOnWindowClosing, write=FOnWindowClosing };
  __property TCppInternetExplorerClientToHostWindow OnClientToHostWindow={ read=FOnClientToHostWindow, write=FOnClientToHostWindow };
  __property TCppInternetExplorerSetSecureLockIcon OnSetSecureLockIcon={ read=FOnSetSecureLockIcon, write=FOnSetSecureLockIcon };
  __property TCppInternetExplorerFileDownload OnFileDownload={ read=FOnFileDownload, write=FOnFileDownload };
  __property TCppInternetExplorerNavigateError OnNavigateError={ read=FOnNavigateError, write=FOnNavigateError };
  __property TCppInternetExplorerPrintTemplateInstantiation OnPrintTemplateInstantiation={ read=FOnPrintTemplateInstantiation, write=FOnPrintTemplateInstantiation };
  __property TCppInternetExplorerPrintTemplateTeardown OnPrintTemplateTeardown={ read=FOnPrintTemplateTeardown, write=FOnPrintTemplateTeardown };
  __property TCppInternetExplorerUpdatePageStatus OnUpdatePageStatus={ read=FOnUpdatePageStatus, write=FOnUpdatePageStatus };
  __property TCppInternetExplorerPrivacyImpactedStateChange OnPrivacyImpactedStateChange={ read=FOnPrivacyImpactedStateChange, write=FOnPrivacyImpactedStateChange };
  __property TCppInternetExplorerNewWindow3 OnNewWindow3={ read=FOnNewWindow3, write=FOnNewWindow3 };
  __property TCppInternetExplorerSetPhishingFilterStatus OnSetPhishingFilterStatus={ read=FOnSetPhishingFilterStatus, write=FOnSetPhishingFilterStatus };
  __property TCppInternetExplorerWindowStateChanged OnWindowStateChanged={ read=FOnWindowStateChanged, write=FOnWindowStateChanged };
  __property TCppInternetExplorerNewProcess OnNewProcess={ read=FOnNewProcess, write=FOnNewProcess };
  __property TCppInternetExplorerThirdPartyUrlBlocked OnThirdPartyUrlBlocked={ read=FOnThirdPartyUrlBlocked, write=FOnThirdPartyUrlBlocked };
  __property TCppInternetExplorerRedirectXDomainBlocked OnRedirectXDomainBlocked={ read=FOnRedirectXDomainBlocked, write=FOnRedirectXDomainBlocked };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TInternetExplorerMedium
// Help String      : Internet Explorer Application with default integrity of Medium
// Default Interface: IWebBrowser2
// Def. Intf. Object: IWebBrowser2Ptr
// Def. Intf. DISP? : No
// Event   Interface: DWebBrowserEvents2
// TypeFlags        : (2) CanCreate
// *********************************************************************//
typedef void __fastcall (__closure * TInternetExplorerMediumStatusTextChange)(System::TObject * Sender, 
                                                                              BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumProgressChange)(System::TObject * Sender, 
                                                                            long Progress/*[in]*/, 
                                                                            long ProgressMax/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumCommandStateChange)(System::TObject * Sender, 
                                                                                long Command/*[in]*/, 
                                                                                VARIANT_BOOL Enable/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumTitleChange)(System::TObject * Sender, 
                                                                         BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumPropertyChange)(System::TObject * Sender, 
                                                                            BSTR szProperty/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumBeforeNavigate2)(System::TObject * Sender, 
                                                                             LPDISPATCH pDisp/*[in]*/, 
                                                                             VARIANT* URL/*[in]*/, 
                                                                             VARIANT* Flags/*[in]*/, 
                                                                             VARIANT* TargetFrameName/*[in]*/, 
                                                                             VARIANT* PostData/*[in]*/, 
                                                                             VARIANT* Headers/*[in]*/, 
                                                                             VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumNewWindow2)(System::TObject * Sender, 
                                                                        LPDISPATCH* ppDisp/*[in,out]*/, 
                                                                        VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumNavigateComplete2)(System::TObject * Sender, 
                                                                               LPDISPATCH pDisp/*[in]*/, 
                                                                               VARIANT* URL/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumDocumentComplete)(System::TObject * Sender, 
                                                                              LPDISPATCH pDisp/*[in]*/, 
                                                                              VARIANT* URL/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumOnVisible)(System::TObject * Sender, 
                                                                       VARIANT_BOOL Visible/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumOnToolBar)(System::TObject * Sender, 
                                                                       VARIANT_BOOL ToolBar/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumOnMenuBar)(System::TObject * Sender, 
                                                                       VARIANT_BOOL MenuBar/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumOnStatusBar)(System::TObject * Sender, 
                                                                         VARIANT_BOOL StatusBar/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumOnFullScreen)(System::TObject * Sender, 
                                                                          VARIANT_BOOL FullScreen/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumOnTheaterMode)(System::TObject * Sender, 
                                                                           VARIANT_BOOL TheaterMode/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowSetResizable)(System::TObject * Sender, 
                                                                                VARIANT_BOOL Resizable/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowSetLeft)(System::TObject * Sender, 
                                                                           long Left/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowSetTop)(System::TObject * Sender, 
                                                                          long Top/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowSetWidth)(System::TObject * Sender, 
                                                                            long Width/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowSetHeight)(System::TObject * Sender, 
                                                                             long Height/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowClosing)(System::TObject * Sender, 
                                                                           VARIANT_BOOL IsChildWindow/*[in]*/, 
                                                                           VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumClientToHostWindow)(System::TObject * Sender, 
                                                                                long* CX/*[in,out]*/, 
                                                                                long* CY/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumSetSecureLockIcon)(System::TObject * Sender, 
                                                                               long SecureLockIcon/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumFileDownload)(System::TObject * Sender, 
                                                                          VARIANT_BOOL ActiveDocument/*[in]*/, 
                                                                          VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumNavigateError)(System::TObject * Sender, 
                                                                           LPDISPATCH pDisp/*[in]*/, 
                                                                           VARIANT* URL/*[in]*/, 
                                                                           VARIANT* Frame/*[in]*/, 
                                                                           VARIANT* StatusCode/*[in]*/, 
                                                                           VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumPrintTemplateInstantiation)(System::TObject * Sender, 
                                                                                        LPDISPATCH pDisp/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumPrintTemplateTeardown)(System::TObject * Sender, 
                                                                                   LPDISPATCH pDisp/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumUpdatePageStatus)(System::TObject * Sender, 
                                                                              LPDISPATCH pDisp/*[in]*/, 
                                                                              VARIANT* nPage/*[in]*/, 
                                                                              VARIANT* fDone/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumPrivacyImpactedStateChange)(System::TObject * Sender, 
                                                                                        VARIANT_BOOL bImpacted/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumNewWindow3)(System::TObject * Sender, 
                                                                        LPDISPATCH* ppDisp/*[in,out]*/, 
                                                                        VARIANT_BOOL* Cancel/*[in,out]*/, 
                                                                        unsigned_long dwFlags/*[in]*/, 
                                                                        BSTR bstrUrlContext/*[in]*/, 
                                                                        BSTR bstrUrl/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumSetPhishingFilterStatus)(System::TObject * Sender, 
                                                                                     long PhishingFilterStatus/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumWindowStateChanged)(System::TObject * Sender, 
                                                                                unsigned_long dwWindowStateFlags/*[in]*/, 
                                                                                unsigned_long dwValidFlagsMask/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumNewProcess)(System::TObject * Sender, 
                                                                        long lCauseFlag/*[in]*/, 
                                                                        LPDISPATCH pWB2/*[in]*/, 
                                                                        VARIANT_BOOL* Cancel/*[in,out]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumThirdPartyUrlBlocked)(System::TObject * Sender, 
                                                                                  VARIANT* URL/*[in]*/, 
                                                                                  unsigned_long dwCount/*[in]*/);
typedef void __fastcall (__closure * TInternetExplorerMediumRedirectXDomainBlocked)(System::TObject * Sender, 
                                                                                    LPDISPATCH pDisp/*[in]*/, 
                                                                                    VARIANT* StartURL/*[in]*/, 
                                                                                    VARIANT* RedirectURL/*[in]*/, 
                                                                                    VARIANT* Frame/*[in]*/, 
                                                                                    VARIANT* StatusCode/*[in]*/);

class PACKAGE TInternetExplorerMedium : public Vcl::Oleserver::TOleServer
{
  IWebBrowser2Ptr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TInternetExplorerMedium(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  IWebBrowser2Ptr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IWebBrowser2Ptr intf);

  virtual void __fastcall InvokeEvent(int DispID, Vcl::Oleserver::TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Application(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Parent(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Container(void);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_Document(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_TopLevelContainer(void);
    // StdProp:WideString
  BSTR            __fastcall get_Type(void);
    // StdProp:Integer
  long            __fastcall get_Left(void);
    // StdProp:Integer
  void            __fastcall set_Left(long pl/*[in]*/);
    // StdProp:Integer
  long            __fastcall get_Top(void);
    // StdProp:Integer
  void            __fastcall set_Top(long pl/*[in]*/);
    // StdProp:Integer
  long            __fastcall get_Width(void);
    // StdProp:Integer
  void            __fastcall set_Width(long pl/*[in]*/);
    // StdProp:Integer
  long            __fastcall get_Height(void);
    // StdProp:Integer
  void            __fastcall set_Height(long pl/*[in]*/);
    // StdProp:WideString
  BSTR            __fastcall get_LocationName(void);
    // StdProp:WideString
  BSTR            __fastcall get_LocationURL(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Busy(void);
    // StdProp:WideString
  BSTR            __fastcall get_Name(void);
    // StdProp:
  long            __fastcall get_HWND(void);
    // StdProp:WideString
  BSTR            __fastcall get_FullName(void);
    // StdProp:WideString
  BSTR            __fastcall get_Path(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Visible(void);
    // StdProp:WordBool
  void            __fastcall set_Visible(VARIANT_BOOL pBool/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_StatusBar(void);
    // StdProp:WordBool
  void            __fastcall set_StatusBar(VARIANT_BOOL pBool/*[in]*/);
    // StdProp:WideString
  BSTR            __fastcall get_StatusText(void);
    // StdProp:WideString
  void            __fastcall set_StatusText(BSTR StatusText/*[in]*/);
    // StdProp:Integer
  int             __fastcall get_ToolBar(void);
    // StdProp:Integer
  void            __fastcall set_ToolBar(int Value/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_MenuBar(void);
    // StdProp:WordBool
  void            __fastcall set_MenuBar(VARIANT_BOOL Value/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_FullScreen(void);
    // StdProp:WordBool
  void            __fastcall set_FullScreen(VARIANT_BOOL pbFullScreen/*[in]*/);
    // StdProp:TOleEnum
  Shdocvw_tlb::tagREADYSTATE __fastcall get_ReadyState(void);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Offline(void);
    // StdProp:WordBool
  void            __fastcall set_Offline(VARIANT_BOOL pbOffline/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Silent(void);
    // StdProp:WordBool
  void            __fastcall set_Silent(VARIANT_BOOL pbSilent/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_RegisterAsBrowser(void);
    // StdProp:WordBool
  void            __fastcall set_RegisterAsBrowser(VARIANT_BOOL pbRegister/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_RegisterAsDropTarget(void);
    // StdProp:WordBool
  void            __fastcall set_RegisterAsDropTarget(VARIANT_BOOL pbRegister/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_TheaterMode(void);
    // StdProp:WordBool
  void            __fastcall set_TheaterMode(VARIANT_BOOL pbRegister/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_AddressBar(void);
    // StdProp:WordBool
  void            __fastcall set_AddressBar(VARIANT_BOOL Value/*[in]*/);
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_Resizable(void);
    // StdProp:WordBool
  void            __fastcall set_Resizable(VARIANT_BOOL Value/*[in]*/);
  /*CoClassWriteMethods*/
  void            __fastcall GoBack(void);
  void            __fastcall GoForward(void);
  void            __fastcall GoHome(void);
  void            __fastcall GoSearch(void);
  void            __fastcall Navigate(BSTR URL/*[in]*/, VARIANT* Flags/*[in,opt]*/= TNoParam(), 
                                      VARIANT* TargetFrameName/*[in,opt]*/= TNoParam(), 
                                      VARIANT* PostData/*[in,opt]*/= TNoParam(), 
                                      VARIANT* Headers/*[in,opt]*/= TNoParam());
  void            __fastcall Refresh(void);
  void            __fastcall Refresh2(VARIANT* Level/*[in,opt]*/= TNoParam());
  void            __fastcall Stop(void);
  void            __fastcall Quit(void);
  void            __fastcall ClientToWindow(int* pcx/*[in,out]*/, int* pcy/*[in,out]*/);
  void            __fastcall PutProperty(BSTR Property/*[in]*/, VARIANT vtValue/*[in]*/);
  VARIANT         __fastcall GetProperty(BSTR Property/*[in]*/);
  void            __fastcall Navigate2(VARIANT* URL/*[in]*/, VARIANT* Flags/*[in,opt]*/= TNoParam(), 
                                       VARIANT* TargetFrameName/*[in,opt]*/= TNoParam(), 
                                       VARIANT* PostData/*[in,opt]*/= TNoParam(), 
                                       VARIANT* Headers/*[in,opt]*/= TNoParam());
  Shdocvw_tlb::OLECMDF __fastcall QueryStatusWB(Shdocvw_tlb::OLECMDID cmdID/*[in]*/);
  void            __fastcall ExecWB(Shdocvw_tlb::OLECMDID cmdID/*[in]*/, 
                                    Shdocvw_tlb::OLECMDEXECOPT cmdexecopt/*[in]*/, 
                                    VARIANT* pvaIn/*[in,opt]*/= TNoParam(), 
                                    VARIANT* pvaOut/*[in,out,opt]*/= TNoParam());
  void            __fastcall ShowBrowserBar(VARIANT* pvaClsid/*[in]*/, 
                                            VARIANT* pvarShow/*[in,opt]*/= TNoParam(), 
                                            VARIANT* pvarSize/*[in,opt]*/= TNoParam());
  /*CoClassWriteProperties*/
  __property LPDISPATCH Application={ read=get_Application }; // STDPROP:0, INTF:No, INVK:2, ID:200, ASSID:200
  __property LPDISPATCH Parent={ read=get_Parent }; // STDPROP:0, INTF:No, INVK:2, ID:201, ASSID:201
  __property LPDISPATCH Container={ read=get_Container }; // STDPROP:0, INTF:No, INVK:2, ID:202, ASSID:202
  __property LPDISPATCH Document={ read=get_Document }; // STDPROP:0, INTF:No, INVK:2, ID:203, ASSID:203
  __property VARIANT_BOOL TopLevelContainer={ read=get_TopLevelContainer }; // STDPROP:0, INTF:No, INVK:2, ID:204, ASSID:204
  __property BSTR Type={ read=get_Type }; // STDPROP:0, INTF:No, INVK:2, ID:205, ASSID:205
  __property BSTR LocationName={ read=get_LocationName }; // STDPROP:0, INTF:No, INVK:2, ID:210, ASSID:210
  __property BSTR LocationURL={ read=get_LocationURL }; // STDPROP:0, INTF:No, INVK:2, ID:211, ASSID:211
  __property VARIANT_BOOL Busy={ read=get_Busy }; // STDPROP:0, INTF:No, INVK:2, ID:212, ASSID:212
  __property BSTR Name={ read=get_Name }; // STDPROP:0, INTF:No, INVK:2, ID:0, ASSID:0
  __property long HWND={ read=get_HWND }; // STDPROP:0, INTF:No, INVK:2, ID:-515, ASSID:-515
  __property BSTR FullName={ read=get_FullName }; // STDPROP:0, INTF:No, INVK:2, ID:400, ASSID:400
  __property BSTR Path={ read=get_Path }; // STDPROP:0, INTF:No, INVK:2, ID:401, ASSID:401
  __property Shdocvw_tlb::tagREADYSTATE ReadyState={ read=get_ReadyState }; // STDPROP:0, INTF:No, INVK:2, ID:-525, ASSID:-525
  /*CoClassWriteProperties*/
  __property long Left={ read=get_Left, write=set_Left, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:206, ASSID:206
  __property long Top={ read=get_Top, write=set_Top, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:207, ASSID:207
  __property long Width={ read=get_Width, write=set_Width, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:208, ASSID:208
  __property long Height={ read=get_Height, write=set_Height, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:209, ASSID:209
  __property VARIANT_BOOL Visible={ read=get_Visible, write=set_Visible, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:402, ASSID:402
  __property VARIANT_BOOL StatusBar={ read=get_StatusBar, write=set_StatusBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:403, ASSID:403
  __property BSTR StatusText={ read=get_StatusText, write=set_StatusText, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:404, ASSID:404
  __property int ToolBar={ read=get_ToolBar, write=set_ToolBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:405, ASSID:405
  __property VARIANT_BOOL MenuBar={ read=get_MenuBar, write=set_MenuBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:406, ASSID:406
  __property VARIANT_BOOL FullScreen={ read=get_FullScreen, write=set_FullScreen, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:407, ASSID:407
  __property VARIANT_BOOL Offline={ read=get_Offline, write=set_Offline, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:550, ASSID:550
  __property VARIANT_BOOL Silent={ read=get_Silent, write=set_Silent, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:551, ASSID:551
  __property VARIANT_BOOL RegisterAsBrowser={ read=get_RegisterAsBrowser, write=set_RegisterAsBrowser, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:552, ASSID:552
  __property VARIANT_BOOL RegisterAsDropTarget={ read=get_RegisterAsDropTarget, write=set_RegisterAsDropTarget, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:553, ASSID:553
  __property VARIANT_BOOL TheaterMode={ read=get_TheaterMode, write=set_TheaterMode, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:554, ASSID:554
  __property VARIANT_BOOL AddressBar={ read=get_AddressBar, write=set_AddressBar, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:555, ASSID:555
  __property VARIANT_BOOL Resizable={ read=get_Resizable, write=set_Resizable, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:556, ASSID:556
  /*CoClassWriteEventDecls*/
private:
  TInternetExplorerMediumStatusTextChange FOnStatusTextChange;
  TInternetExplorerMediumProgressChange FOnProgressChange;
  TInternetExplorerMediumCommandStateChange FOnCommandStateChange;
  System::Classes::TNotifyEvent  FOnDownloadBegin;
  System::Classes::TNotifyEvent  FOnDownloadComplete;
  TInternetExplorerMediumTitleChange FOnTitleChange;
  TInternetExplorerMediumPropertyChange FOnPropertyChange;
  TInternetExplorerMediumBeforeNavigate2 FOnBeforeNavigate2;
  TInternetExplorerMediumNewWindow2 FOnNewWindow2;
  TInternetExplorerMediumNavigateComplete2 FOnNavigateComplete2;
  TInternetExplorerMediumDocumentComplete FOnDocumentComplete;
  System::Classes::TNotifyEvent  FOnQuit;
  TInternetExplorerMediumOnVisible FOnVisible;
  TInternetExplorerMediumOnToolBar FOnToolBar;
  TInternetExplorerMediumOnMenuBar FOnMenuBar;
  TInternetExplorerMediumOnStatusBar FOnStatusBar;
  TInternetExplorerMediumOnFullScreen FOnFullScreen;
  TInternetExplorerMediumOnTheaterMode FOnTheaterMode;
  TInternetExplorerMediumWindowSetResizable FOnWindowSetResizable;
  TInternetExplorerMediumWindowSetLeft FOnWindowSetLeft;
  TInternetExplorerMediumWindowSetTop FOnWindowSetTop;
  TInternetExplorerMediumWindowSetWidth FOnWindowSetWidth;
  TInternetExplorerMediumWindowSetHeight FOnWindowSetHeight;
  TInternetExplorerMediumWindowClosing FOnWindowClosing;
  TInternetExplorerMediumClientToHostWindow FOnClientToHostWindow;
  TInternetExplorerMediumSetSecureLockIcon FOnSetSecureLockIcon;
  TInternetExplorerMediumFileDownload FOnFileDownload;
  TInternetExplorerMediumNavigateError FOnNavigateError;
  TInternetExplorerMediumPrintTemplateInstantiation FOnPrintTemplateInstantiation;
  TInternetExplorerMediumPrintTemplateTeardown FOnPrintTemplateTeardown;
  TInternetExplorerMediumUpdatePageStatus FOnUpdatePageStatus;
  TInternetExplorerMediumPrivacyImpactedStateChange FOnPrivacyImpactedStateChange;
  TInternetExplorerMediumNewWindow3 FOnNewWindow3;
  TInternetExplorerMediumSetPhishingFilterStatus FOnSetPhishingFilterStatus;
  TInternetExplorerMediumWindowStateChanged FOnWindowStateChanged;
  TInternetExplorerMediumNewProcess FOnNewProcess;
  TInternetExplorerMediumThirdPartyUrlBlocked FOnThirdPartyUrlBlocked;
  TInternetExplorerMediumRedirectXDomainBlocked FOnRedirectXDomainBlocked;
__published:
  __property TInternetExplorerMediumStatusTextChange OnStatusTextChange={ read=FOnStatusTextChange, write=FOnStatusTextChange };
  __property TInternetExplorerMediumProgressChange OnProgressChange={ read=FOnProgressChange, write=FOnProgressChange };
  __property TInternetExplorerMediumCommandStateChange OnCommandStateChange={ read=FOnCommandStateChange, write=FOnCommandStateChange };
  __property System::Classes::TNotifyEvent OnDownloadBegin={ read=FOnDownloadBegin, write=FOnDownloadBegin };
  __property System::Classes::TNotifyEvent OnDownloadComplete={ read=FOnDownloadComplete, write=FOnDownloadComplete };
  __property TInternetExplorerMediumTitleChange OnTitleChange={ read=FOnTitleChange, write=FOnTitleChange };
  __property TInternetExplorerMediumPropertyChange OnPropertyChange={ read=FOnPropertyChange, write=FOnPropertyChange };
  __property TInternetExplorerMediumBeforeNavigate2 OnBeforeNavigate2={ read=FOnBeforeNavigate2, write=FOnBeforeNavigate2 };
  __property TInternetExplorerMediumNewWindow2 OnNewWindow2={ read=FOnNewWindow2, write=FOnNewWindow2 };
  __property TInternetExplorerMediumNavigateComplete2 OnNavigateComplete2={ read=FOnNavigateComplete2, write=FOnNavigateComplete2 };
  __property TInternetExplorerMediumDocumentComplete OnDocumentComplete={ read=FOnDocumentComplete, write=FOnDocumentComplete };
  __property System::Classes::TNotifyEvent OnQuit={ read=FOnQuit, write=FOnQuit };
  __property TInternetExplorerMediumOnVisible OnVisible={ read=FOnVisible, write=FOnVisible };
  __property TInternetExplorerMediumOnToolBar OnToolBar={ read=FOnToolBar, write=FOnToolBar };
  __property TInternetExplorerMediumOnMenuBar OnMenuBar={ read=FOnMenuBar, write=FOnMenuBar };
  __property TInternetExplorerMediumOnStatusBar OnStatusBar={ read=FOnStatusBar, write=FOnStatusBar };
  __property TInternetExplorerMediumOnFullScreen OnFullScreen={ read=FOnFullScreen, write=FOnFullScreen };
  __property TInternetExplorerMediumOnTheaterMode OnTheaterMode={ read=FOnTheaterMode, write=FOnTheaterMode };
  __property TInternetExplorerMediumWindowSetResizable OnWindowSetResizable={ read=FOnWindowSetResizable, write=FOnWindowSetResizable };
  __property TInternetExplorerMediumWindowSetLeft OnWindowSetLeft={ read=FOnWindowSetLeft, write=FOnWindowSetLeft };
  __property TInternetExplorerMediumWindowSetTop OnWindowSetTop={ read=FOnWindowSetTop, write=FOnWindowSetTop };
  __property TInternetExplorerMediumWindowSetWidth OnWindowSetWidth={ read=FOnWindowSetWidth, write=FOnWindowSetWidth };
  __property TInternetExplorerMediumWindowSetHeight OnWindowSetHeight={ read=FOnWindowSetHeight, write=FOnWindowSetHeight };
  __property TInternetExplorerMediumWindowClosing OnWindowClosing={ read=FOnWindowClosing, write=FOnWindowClosing };
  __property TInternetExplorerMediumClientToHostWindow OnClientToHostWindow={ read=FOnClientToHostWindow, write=FOnClientToHostWindow };
  __property TInternetExplorerMediumSetSecureLockIcon OnSetSecureLockIcon={ read=FOnSetSecureLockIcon, write=FOnSetSecureLockIcon };
  __property TInternetExplorerMediumFileDownload OnFileDownload={ read=FOnFileDownload, write=FOnFileDownload };
  __property TInternetExplorerMediumNavigateError OnNavigateError={ read=FOnNavigateError, write=FOnNavigateError };
  __property TInternetExplorerMediumPrintTemplateInstantiation OnPrintTemplateInstantiation={ read=FOnPrintTemplateInstantiation, write=FOnPrintTemplateInstantiation };
  __property TInternetExplorerMediumPrintTemplateTeardown OnPrintTemplateTeardown={ read=FOnPrintTemplateTeardown, write=FOnPrintTemplateTeardown };
  __property TInternetExplorerMediumUpdatePageStatus OnUpdatePageStatus={ read=FOnUpdatePageStatus, write=FOnUpdatePageStatus };
  __property TInternetExplorerMediumPrivacyImpactedStateChange OnPrivacyImpactedStateChange={ read=FOnPrivacyImpactedStateChange, write=FOnPrivacyImpactedStateChange };
  __property TInternetExplorerMediumNewWindow3 OnNewWindow3={ read=FOnNewWindow3, write=FOnNewWindow3 };
  __property TInternetExplorerMediumSetPhishingFilterStatus OnSetPhishingFilterStatus={ read=FOnSetPhishingFilterStatus, write=FOnSetPhishingFilterStatus };
  __property TInternetExplorerMediumWindowStateChanged OnWindowStateChanged={ read=FOnWindowStateChanged, write=FOnWindowStateChanged };
  __property TInternetExplorerMediumNewProcess OnNewProcess={ read=FOnNewProcess, write=FOnNewProcess };
  __property TInternetExplorerMediumThirdPartyUrlBlocked OnThirdPartyUrlBlocked={ read=FOnThirdPartyUrlBlocked, write=FOnThirdPartyUrlBlocked };
  __property TInternetExplorerMediumRedirectXDomainBlocked OnRedirectXDomainBlocked={ read=FOnRedirectXDomainBlocked, write=FOnRedirectXDomainBlocked };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TCppShellWindows
// Help String      : ShellDispatch Load in Shell Context
// Default Interface: IShellWindows
// Def. Intf. Object: IShellWindowsPtr
// Def. Intf. DISP? : No
// Event   Interface: DShellWindowsEvents
// TypeFlags        : (2) CanCreate
// *********************************************************************//
typedef void __fastcall (__closure * TCppShellWindowsWindowRegistered)(System::TObject * Sender, 
                                                                       long lCookie/*[in]*/);
typedef void __fastcall (__closure * TCppShellWindowsWindowRevoked)(System::TObject * Sender, 
                                                                    long lCookie/*[in]*/);

class PACKAGE TCppShellWindows : public Vcl::Oleserver::TOleServer
{
  IShellWindowsPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TCppShellWindows(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  IShellWindowsPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IShellWindowsPtr intf);

  virtual void __fastcall InvokeEvent(int DispID, Vcl::Oleserver::TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
    // StdProp:Integer
  long            __fastcall get_Count(void);
  /*CoClassWriteMethods*/
  LPDISPATCH      __fastcall Item(VARIANT index/*[in,opt]*/= TNoParam());
  LPUNKNOWN       __fastcall _NewEnum(void);
  void            __fastcall Register(LPDISPATCH pid/*[in]*/, long HWND/*[in]*/, int swClass/*[in]*/, 
                                      long* plCookie/*[out]*/);
  void            __fastcall RegisterPending(long lThreadId/*[in]*/, VARIANT* pvarloc/*[in]*/, 
                                             VARIANT* pvarlocRoot/*[in]*/, int swClass/*[in]*/, 
                                             long* plCookie/*[out]*/);
  void            __fastcall Revoke(long lCookie/*[in]*/);
  void            __fastcall OnNavigate(long lCookie/*[in]*/, VARIANT* pvarloc/*[in]*/);
  void            __fastcall OnActivated(long lCookie/*[in]*/, VARIANT_BOOL fActive/*[in]*/);
  LPDISPATCH      __fastcall FindWindowSW(VARIANT* pvarloc/*[in]*/, VARIANT* pvarlocRoot/*[in]*/, 
                                          int swClass/*[in]*/, long* pHWND/*[out]*/, 
                                          int swfwOptions/*[in]*/);
  void            __fastcall OnCreated(long lCookie/*[in]*/, LPUNKNOWN punk/*[in]*/);
  void            __fastcall ProcessAttachDetach(VARIANT_BOOL fAttach/*[in]*/);
  /*CoClassWriteProperties*/
  __property long Count={ read=get_Count }; // STDPROP:0, INTF:No, INVK:2, ID:-1, ASSID:1610743808
  /*CoClassWriteProperties*/
  /*CoClassWriteEventDecls*/
private:
  TCppShellWindowsWindowRegistered FOnWindowRegistered;
  TCppShellWindowsWindowRevoked  FOnWindowRevoked;
__published:
  __property TCppShellWindowsWindowRegistered OnWindowRegistered={ read=FOnWindowRegistered, write=FOnWindowRegistered };
  __property TCppShellWindowsWindowRevoked OnWindowRevoked={ read=FOnWindowRevoked, write=FOnWindowRevoked };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TCppShellUIHelper
// Help String      : 
// Default Interface: IShellUIHelper3
// Def. Intf. Object: IShellUIHelper3Ptr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TCppShellUIHelper : public Vcl::Oleserver::TOleServer
{
  IShellUIHelper3Ptr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TCppShellUIHelper(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  IShellUIHelper3Ptr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IShellUIHelper3Ptr intf);


  /*CoClassWriteArrayPropMethods*/
  /*CoClassWriteMethods*/
  void            __fastcall ResetFirstBootMode(void);
  void            __fastcall ResetSafeMode(void);
  void            __fastcall RefreshOfflineDesktop(void);
  void            __fastcall AddFavorite(BSTR URL/*[in]*/, VARIANT* Title/*[in,opt]*/= TNoParam());
  void            __fastcall AddChannel(BSTR URL/*[in]*/);
  void            __fastcall AddDesktopComponent(BSTR URL/*[in]*/, BSTR Type/*[in]*/, 
                                                 VARIANT* Left/*[in,opt]*/= TNoParam(), 
                                                 VARIANT* Top/*[in,opt]*/= TNoParam(), 
                                                 VARIANT* Width/*[in,opt]*/= TNoParam(), 
                                                 VARIANT* Height/*[in,opt]*/= TNoParam());
  VARIANT_BOOL    __fastcall IsSubscribed(BSTR URL/*[in]*/);
  void            __fastcall NavigateAndFind(BSTR URL/*[in]*/, BSTR strQuery/*[in]*/, 
                                             VARIANT* varTargetFrame/*[in]*/);
  void            __fastcall ImportExportFavorites(VARIANT_BOOL fImport/*[in]*/, 
                                                   BSTR strImpExpPath/*[in]*/);
  void            __fastcall AutoCompleteSaveForm(VARIANT* Form/*[in,opt]*/= TNoParam());
  void            __fastcall AutoScan(BSTR strSearch/*[in]*/, BSTR strFailureUrl/*[in]*/, 
                                      VARIANT* pvarTargetFrame/*[in,opt]*/= TNoParam());
  void            __fastcall AutoCompleteAttach(VARIANT* Reserved/*[in,opt]*/= TNoParam());
  VARIANT         __fastcall ShowBrowserUI(BSTR bstrName/*[in]*/, VARIANT* pvarIn/*[in]*/);
  void            __fastcall AddSearchProvider(BSTR URL/*[in]*/);
  void            __fastcall RunOnceShown(void);
  void            __fastcall SkipRunOnce(void);
  void            __fastcall CustomizeSettings(VARIANT_BOOL fSQM/*[in]*/, 
                                               VARIANT_BOOL fPhishing/*[in]*/, 
                                               BSTR bstrLocale/*[in]*/);
  VARIANT_BOOL    __fastcall SqmEnabled(void);
  VARIANT_BOOL    __fastcall PhishingEnabled(void);
  BSTR            __fastcall BrandImageUri(void);
  void            __fastcall SkipTabsWelcome(void);
  void            __fastcall DiagnoseConnection(void);
  void            __fastcall CustomizeClearType(VARIANT_BOOL fSet/*[in]*/);
  unsigned_long   __fastcall IsSearchProviderInstalled(BSTR URL/*[in]*/);
  VARIANT_BOOL    __fastcall IsSearchMigrated(void);
  BSTR            __fastcall DefaultSearchProvider(void);
  void            __fastcall RunOnceRequiredSettingsComplete(VARIANT_BOOL fComplete/*[in]*/);
  VARIANT_BOOL    __fastcall RunOnceHasShown(void);
  BSTR            __fastcall SearchGuideUrl(void);
  void            __fastcall AddService(BSTR URL/*[in]*/);
  unsigned_long   __fastcall IsServiceInstalled(BSTR URL/*[in]*/, BSTR Verb/*[in]*/);
  VARIANT_BOOL    __fastcall InPrivateFilteringEnabled(void);
  void            __fastcall AddToFavoritesBar(BSTR URL/*[in]*/, BSTR Title/*[in]*/, 
                                               VARIANT* Type/*[in,opt]*/= TNoParam());
  void            __fastcall BuildNewTabPage(void);
  void            __fastcall SetRecentlyClosedVisible(VARIANT_BOOL fVisible/*[in]*/);
  void            __fastcall SetActivitiesVisible(VARIANT_BOOL fVisible/*[in]*/);
  void            __fastcall ContentDiscoveryReset(void);
  VARIANT_BOOL    __fastcall IsSuggestedSitesEnabled(void);
  void            __fastcall EnableSuggestedSites(VARIANT_BOOL fEnable/*[in]*/);
  void            __fastcall NavigateToSuggestedSites(BSTR bstrRelativeUrl/*[in]*/);
  void            __fastcall ShowTabsHelp(void);
  void            __fastcall ShowInPrivateHelp(void);
  /*CoClassWriteProperties*/
  /*CoClassWriteProperties*/
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TShellFavoritesNameSpace
// Help String      : 
// Default Interface: IShellNameSpace
// Def. Intf. Object: IShellNameSpacePtr
// Def. Intf. DISP? : No
// Event   Interface: DShellNameSpaceEvents
// TypeFlags        : (2) CanCreate
// *********************************************************************//
typedef void __fastcall (__closure * TShellFavoritesNameSpaceFavoritesSelectionChange)(System::TObject * Sender, 
                                                                                       long cItems/*[in]*/, 
                                                                                       long hItem/*[in]*/, 
                                                                                       BSTR strName/*[in]*/, 
                                                                                       BSTR strUrl/*[in]*/, 
                                                                                       long cVisits/*[in]*/, 
                                                                                       BSTR strDate/*[in]*/, 
                                                                                       long fAvailableOffline/*[in]*/);

class PACKAGE TShellFavoritesNameSpace : public Vcl::Oleserver::TOleServer
{
  IShellNameSpacePtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TShellFavoritesNameSpace(System::Classes::TComponent* owner) : Vcl::Oleserver::TOleServer(owner)
  {}

  IShellNameSpacePtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IShellNameSpacePtr intf);

  virtual void __fastcall InvokeEvent(int DispID, Vcl::Oleserver::TVariantArray& params);

  /*CoClassWriteArrayPropMethods*/
    // StdProp:WordBool
  VARIANT_BOOL    __fastcall get_SubscriptionsEnabled(void);
    // StdProp:Integer
  long            __fastcall get_EnumOptions(void);
    // StdProp:Integer
  void            __fastcall set_EnumOptions(long pgrfEnumFlags/*[in]*/);
    // StdProp:IDispatch
  LPDISPATCH      __fastcall get_SelectedItem(void);
    // StdProp:IDispatch
  void            __fastcall set_SelectedItem(LPDISPATCH pItem/*[in]*/);
    // StdProp:OleVariant
  VARIANT         __fastcall get_Root(void);
    // StdProp:OleVariant
  void            __fastcall set_Root(VARIANT pvar/*[in]*/);
    // StdProp:Integer
  int             __fastcall get_Depth(void);
    // StdProp:Integer
  void            __fastcall set_Depth(int piDepth/*[in]*/);
    // StdProp:Integer
  unsigned        __fastcall get_Mode(void);
    // StdProp:Integer
  void            __fastcall set_Mode(unsigned puMode/*[in]*/);
    // StdProp:Integer
  unsigned_long   __fastcall get_Flags(void);
    // StdProp:Integer
  void            __fastcall set_Flags(unsigned_long pdwFlags/*[in]*/);
    // StdProp:Integer
  void            __fastcall set_TVFlags(unsigned_long dwFlags/*[in]*/);
    // StdProp:Integer
  unsigned_long   __fastcall get_TVFlags(void);
    // StdProp:WideString
  BSTR            __fastcall get_Columns(void);
    // StdProp:WideString
  void            __fastcall set_Columns(BSTR bstrColumns/*[in]*/);
    // StdProp:Integer
  int             __fastcall get_CountViewTypes(void);
  /*CoClassWriteMethods*/
  void            __fastcall MoveSelectionUp(void);
  void            __fastcall MoveSelectionDown(void);
  void            __fastcall ResetSort(void);
  void            __fastcall NewFolder(void);
  void            __fastcall Synchronize(void);
  void            __fastcall Import(void);
  void            __fastcall Export(void);
  void            __fastcall InvokeContextMenuCommand(BSTR strCommand/*[in]*/);
  void            __fastcall MoveSelectionTo(void);
  VARIANT_BOOL    __fastcall CreateSubscriptionForSelection(void);
  VARIANT_BOOL    __fastcall DeleteSubscriptionForSelection(void);
  void            __fastcall SetRoot(BSTR bstrFullPath/*[in]*/);
  void            __fastcall SetViewType(int iType/*[in]*/);
  LPDISPATCH      __fastcall SelectedItems(void);
  void            __fastcall Expand(VARIANT var/*[in]*/, int iDepth);
  void            __fastcall UnselectAll(void);
  /*CoClassWriteProperties*/
  __property VARIANT_BOOL SubscriptionsEnabled={ read=get_SubscriptionsEnabled }; // STDPROP:0, INTF:No, INVK:2, ID:10, ASSID:10
  __property LPDISPATCH SelectedItem={ read=get_SelectedItem, write=set_SelectedItem }; // STDPROP:0, INTF:No, INVK:2, ID:15, ASSID:15
  __property VARIANT Root={ read=get_Root, write=set_Root }; // STDPROP:0, INTF:No, INVK:2, ID:16, ASSID:16
  __property int CountViewTypes={ read=get_CountViewTypes }; // STDPROP:0, INTF:No, INVK:2, ID:22, ASSID:22
  /*CoClassWriteProperties*/
  __property long EnumOptions={ read=get_EnumOptions, write=set_EnumOptions, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:14, ASSID:14
  __property int Depth={ read=get_Depth, write=set_Depth, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:17, ASSID:17
  __property unsigned Mode={ read=get_Mode, write=set_Mode, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:18, ASSID:18
  __property unsigned_long Flags={ read=get_Flags, write=set_Flags, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:19, ASSID:19
  __property unsigned_long TVFlags={ read=get_TVFlags, write=set_TVFlags, stored=false }; // STDPROP:0, INTF:No, INVK:4, ID:20, ASSID:20
  __property BSTR Columns={ read=get_Columns, write=set_Columns, stored=false }; // STDPROP:0, INTF:No, INVK:2, ID:21, ASSID:21
  /*CoClassWriteEventDecls*/
private:
  TShellFavoritesNameSpaceFavoritesSelectionChange FOnFavoritesSelectionChange;
  System::Classes::TNotifyEvent  FOnSelectionChange;
  System::Classes::TNotifyEvent  FOnDoubleClick;
  System::Classes::TNotifyEvent  FOnInitialized;
__published:
  __property TShellFavoritesNameSpaceFavoritesSelectionChange OnFavoritesSelectionChange={ read=FOnFavoritesSelectionChange, write=FOnFavoritesSelectionChange };
  __property System::Classes::TNotifyEvent OnSelectionChange={ read=FOnSelectionChange, write=FOnSelectionChange };
  __property System::Classes::TNotifyEvent OnDoubleClick={ read=FOnDoubleClick, write=FOnDoubleClick };
  __property System::Classes::TNotifyEvent OnInitialized={ read=FOnInitialized, write=FOnInitialized };
};

};     // namespace Shdocvw_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Shdocvw_tlb;
#endif

#pragma pack(pop)
#pragma option pop

#endif // SHDocVw_OCXH
